// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using paypal_final.Data;

namespace paypal_final.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200315235342_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("paypal_final.Data.IPN", b =>
                {
                    b.Property<string>("paymentID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("amount");

                    b.Property<string>("cart");

                    b.Property<string>("create_time");

                    b.Property<string>("currency");

                    b.Property<string>("custom");

                    b.Property<string>("intent");

                    b.Property<string>("payerCountryCode");

                    b.Property<string>("payerEmail");

                    b.Property<string>("payerFirstName");

                    b.Property<string>("payerID");

                    b.Property<string>("payerLastName");

                    b.Property<string>("payerMiddleName");

                    b.Property<string>("payerStatus");

                    b.Property<string>("paymentMethod");

                    b.Property<string>("paymentState");

                    b.HasKey("paymentID");

                    b.ToTable("IPNs");
                });
#pragma warning restore 612, 618
        }
    }
}
